# Generated by Django 4.2 on 2023-04-27 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account_Data",
            fields=[
                ("Accno", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "Balance_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("USD", "US Dollar $"),
                            ("EUR", "Euro €"),
                            ("GBP", "British Pound £"),
                        ],
                        default=None,
                        editable=False,
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "Balance",
                    djmoney.models.fields.MoneyField(
                        currency_choices=[
                            ("USD", "US Dollar $"),
                            ("EUR", "Euro €"),
                            ("GBP", "British Pound £"),
                        ],
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                    ),
                ),
            ],
            options={"db_table": "account",},
        ),
        migrations.CreateModel(
            name="conversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency1_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("USD", "US Dollar $"),
                            ("EUR", "Euro €"),
                            ("GBP", "British Pound £"),
                        ],
                        default=None,
                        editable=False,
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "currency1",
                    djmoney.models.fields.MoneyField(
                        currency_choices=[
                            ("USD", "US Dollar $"),
                            ("EUR", "Euro €"),
                            ("GBP", "British Pound £"),
                        ],
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "currency2_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("USD", "US Dollar $"),
                            ("EUR", "Euro €"),
                            ("GBP", "British Pound £"),
                        ],
                        default=None,
                        editable=False,
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "currency2",
                    djmoney.models.fields.MoneyField(
                        currency_choices=[
                            ("USD", "US Dollar $"),
                            ("EUR", "Euro €"),
                            ("GBP", "British Pound £"),
                        ],
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                    ),
                ),
                ("rate", models.DecimalField(decimal_places=2, max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name="Deposits",
            fields=[
                ("Trans_ID", models.AutoField(primary_key=True, serialize=False)),
                ("Accno", models.IntegerField()),
                (
                    "Amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("EUR", "EUR €"), ("GBP", "GBP £"), ("USD", "USD $")],
                        default=None,
                        editable=False,
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "Amount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2, max_digits=14, null=True
                    ),
                ),
            ],
            options={"db_table": "deposits",},
        ),
        migrations.CreateModel(
            name="Money_Transfers",
            fields=[
                ("Trans_ID", models.AutoField(primary_key=True, serialize=False)),
                ("sender", models.IntegerField()),
                ("receiver", models.IntegerField()),
                (
                    "Amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("EUR", "EUR €"), ("GBP", "GBP £"), ("USD", "USD $")],
                        default=None,
                        editable=False,
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "Amount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2, max_digits=14, null=True
                    ),
                ),
            ],
            options={"db_table": "transfers",},
        ),
        migrations.CreateModel(
            name="PaymentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender", models.CharField(max_length=50)),
                ("receiver", models.CharField(max_length=50)),
                ("reason", models.CharField(max_length=255)),
                (
                    "Amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("EUR", "EUR €"), ("GBP", "GBP £"), ("USD", "USD $")],
                        default=None,
                        editable=False,
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "Amount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("status", models.CharField(default="pending", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="User_Account",
            fields=[
                ("Cust_ID", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
            ],
            options={"db_table": "customer",},
        ),
        migrations.CreateModel(
            name="Withdraws",
            fields=[
                ("Trans_ID", models.AutoField(primary_key=True, serialize=False)),
                ("Accno", models.IntegerField()),
                (
                    "Amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("EUR", "EUR €"), ("GBP", "GBP £"), ("USD", "USD $")],
                        default=None,
                        editable=False,
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "Amount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2, max_digits=14, null=True
                    ),
                ),
            ],
            options={"db_table": "withdraws",},
        ),
        migrations.CreateModel(
            name="Transactions",
            fields=[
                ("Trans_ID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "Amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("EUR", "EUR €"), ("GBP", "GBP £"), ("USD", "USD $")],
                        default="USD",
                        editable=False,
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "Amount",
                    djmoney.models.fields.MoneyField(
                        choices=[
                            ("USD", "US Dollar $"),
                            ("EUR", "Euro €"),
                            ("GBP", "British Pound £"),
                        ],
                        decimal_places=2,
                        default_currency="USD",
                        max_digits=14,
                        null=True,
                    ),
                ),
                ("Type", models.CharField(max_length=30)),
                ("Date", models.DateField(auto_now_add=True)),
                ("Time", models.TimeField()),
                (
                    "Accno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payapp.account_data",
                    ),
                ),
            ],
            options={"db_table": "transactions",},
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("EUR", "EUR €"), ("GBP", "GBP £"), ("USD", "USD $")],
                        default=None,
                        editable=False,
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "Amount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("payment_method", models.CharField(max_length=20)),
                ("transaction_id", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payapp.paymentrequest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("Not_ID", models.AutoField(primary_key=True, serialize=False)),
                ("reason", models.TextField()),
                ("Amount", models.FloatField()),
                ("status", models.CharField(default="pending", max_length=20)),
                ("timestamp", models.DateField(auto_now_add=True)),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receiver",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sender",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "Notification",},
        ),
        migrations.AddField(
            model_name="account_data",
            name="Owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="payapp.user_account"
            ),
        ),
    ]
